export const projects = {
    "Projects": {
        "Kamrani%20Kaizen": [
            require("./img/projects/kamraniKaizenTirunelveli/1.jpeg"),
            require("./img/projects/kamraniKaizenTirunelveli/2.jpeg"),
            require("./img/projects/kamraniKaizenTirunelveli/3.jpeg"),
            require("./img/projects/kamraniKaizenTirunelveli/4.jpeg"),
            require("./img/projects/kamraniKaizenTirunelveli/5.jpeg"),
            require("./img/projects/kamraniKaizenTirunelveli/6.jpeg"),
        ],
        "Basavanagudi": [
            require("./img/projects/basavanagudi/1.jpg"),
            require("./img/projects/basavanagudi/2.JPG"),
            require("./img/projects/basavanagudi/3.JPG"),
            require("./img/projects/basavanagudi/4.JPG"),
            require("./img/projects/basavanagudi/5.JPG"),
            require("./img/projects/basavanagudi/6.JPG"),
        ],
        "Green%20Enclave": [
            require("./img/projects/greenEnclave/1.JPG"),
            require("./img/projects/greenEnclave/2.jpg"),
            require("./img/projects/greenEnclave/3.JPG"),
            require("./img/projects/greenEnclave/4.JPG"),
            require("./img/projects/greenEnclave/5.JPG"),
            require("./img/projects/greenEnclave/6.JPG"),
            require("./img/projects/greenEnclave/7.JPG"),
            require("./img/projects/greenEnclave/8.jpg"),
            require("./img/projects/greenEnclave/9.JPG"),
            require("./img/projects/greenEnclave/10.jpg"),
            require("./img/projects/greenEnclave/11.JPG"),
            require("./img/projects/greenEnclave/12.JPG"),
            require("./img/projects/greenEnclave/13.jpg"),
            require("./img/projects/greenEnclave/14.JPG"),
            require("./img/projects/greenEnclave/15.JPG"),
            require("./img/projects/greenEnclave/16.JPG"),
            require("./img/projects/greenEnclave/17.jpg"),
            require("./img/projects/greenEnclave/18.JPG"),
            require("./img/projects/greenEnclave/19.JPG"),
            require("./img/projects/greenEnclave/20.JPG"),
            require("./img/projects/greenEnclave/21.JPG"),
            require("./img/projects/greenEnclave/22.JPG"),

        ],
        "Banglore%20Telephone%20Layout": [
            require("./img/projects/bangloreTelephoneLayout/1.jpeg"),
        ],
        "Chennai%20Roopas%20Residency": [
            require("./img/projects/chennaiRoopasResidency/1.jpeg"),
            require("./img/projects/chennaiRoopasResidency/2.jpeg"),
        ],
        "Ganga%20Nagar": [
            require("./img/projects/gangaNagarAslamsResidence/1.jpeg"),
        ],
        "HBR": [
            require("./img/projects/hbr/1.jpg"),
            require("./img/projects/hbr/2.jpg"),
            require("./img/projects/hbr/3.jpg"),
            require("./img/projects/hbr/4.jpg"),
            require("./img/projects/hbr/5.jpg"),
            require("./img/projects/hbr/6.jpg"),
            require("./img/projects/hbr/7.jpg"),
            require("./img/projects/hbr/8.jpg"),
            require("./img/projects/hbr/9.jpg"),
            require("./img/projects/hbr/10.jpg"),
            require("./img/projects/hbr/11.jpg"),
            require("./img/projects/hbr/12.jpg"),
            require("./img/projects/hbr/13.jpg"),
        ],
        "HBR1": [
            require("./img/projects/hbr1/1.jpeg"),
            require("./img/projects/hbr1/2.jpeg"),
            require("./img/projects/hbr1/3.jpeg"),
            require("./img/projects/hbr1/4.jpeg"),
            require("./img/projects/hbr1/5.jpeg"),
            require("./img/projects/hbr1/6.jpg"),
            require("./img/projects/hbr1/7.jpeg"),
            require("./img/projects/hbr1/8.jpeg"),
            require("./img/projects/hbr1/9.jpeg"),
            require("./img/projects/hbr1/10.jpeg"),
            require("./img/projects/hbr1/11.jpeg"),
        ],
        "Lingarajpuram": [
            require("./img/projects/lingarajpuram/1.jpg"),
            require("./img/projects/lingarajpuram/2.jpg"),
            require("./img/projects/lingarajpuram/3.jpg"),
            require("./img/projects/lingarajpuram/4.jpg"),
            require("./img/projects/lingarajpuram/5.jpg"),
            require("./img/projects/lingarajpuram/6.jpg"),
            require("./img/projects/lingarajpuram/7.jpg"),
            require("./img/projects/lingarajpuram/8.jpg"),
            require("./img/projects/lingarajpuram/9.jpg"),
            require("./img/projects/lingarajpuram/10.jpg"),
            require("./img/projects/lingarajpuram/11.jpg"),
            require("./img/projects/lingarajpuram/12.jpg"),
        ],
        "Loyd's%20Road": [
            require("./img/projects/loydsroadbanglore/1.jpeg"),
            require("./img/projects/loydsroadbanglore/2.jpeg"),
            require("./img/projects/loydsroadbanglore/3.jpeg"),
            require("./img/projects/loydsroadbanglore/4.jpeg"),
            require("./img/projects/loydsroadbanglore/5.jpeg"),
            require("./img/projects/loydsroadbanglore/6.jpeg"),
        ],
        "Pearl%20Nest": [
            require("./img/projects/pearlNestvadapalinichennai/1.jpeg"),
            require("./img/projects/pearlNestvadapalinichennai/2.jpeg"),
        ],
        "Kamanahali": [
            require("./img/projects/kamanahali/1.jpg"),
            require("./img/projects/kamanahali/2.jpg"),
            require("./img/projects/kamanahali/3.jpg"),
            require("./img/projects/kamanahali/4.jpg"),
            require("./img/projects/kamanahali/5.jpg"),
            require("./img/projects/kamanahali/6.jpg"),
            require("./img/projects/kamanahali/7.jpg"),
            require("./img/projects/kamanahali/8.jpg"),
            require("./img/projects/kamanahali/9.jpg"),
            require("./img/projects/kamanahali/10.jpg"),
            require("./img/projects/kamanahali/11.jpg"),
            require("./img/projects/kamanahali/11.jpg"),
            require("./img/projects/kamanahali/12.jpg"),
            require("./img/projects/kamanahali/13.jpg"),
            require("./img/projects/kamanahali/14.jpg"),
            require("./img/projects/kamanahali/15.jpg"),
        ],
        "Yeshwanthpur": [
            require("./img/projects/yeshwanthpur/1.jpeg"),
            require("./img/projects/yeshwanthpur/2.jpeg"),
            require("./img/projects/yeshwanthpur/3.jpeg"),

        ],
        "Mosque%20Road": [
            require("./img/projects/mosqueroadbengalore/1.jpeg"),
        ],
        "Interior": [
            require("./img/projects/interior/1.jpeg"),
            require("./img/projects/interior/2.jpeg"),
            require("./img/projects/interior/3.jpeg"),
            require("./img/projects/interior/4.jpeg"),
            require("./img/projects/interior/5.jpeg"),
            require("./img/projects/interior/6.jpeg"),
            require("./img/projects/interior/7.jpeg"),
            require("./img/projects/interior/8.jpeg"),
            require("./img/projects/interior/9.jpeg"),
            require("./img/projects/interior/10.jpeg"),
            require("./img/projects/interior/11.jpeg"),
            require("./img/projects/interior/12.jpeg"),
            require("./img/projects/interior/13.jpeg"),
            require("./img/projects/interior/14.jpeg"),
            require("./img/projects/interior/15.jpeg"),
            require("./img/projects/interior/16.jpeg"),
            require("./img/projects/interior/17.jpeg"),

        ],
    }
}